application:
  port: 8000
database:
  host: "127.0.0.1"
  port: 5433
  username: "postgres"
  password: "password"
  name: "newsletter"
email_client:
  base_url: "http://localhost"
  sender_email: "test@gmail.com"
  # We are only setting the development value,
  # we'll deal with the production token outside of version control # (given that it's a sensitive secret!)
  authorization_token: "my-secret-token"
  timeout_ms: 10000
